apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: go-nkgrnvfi
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/jsmid/go-nkgrnvfi:azure-e1a0b1fb553d83ac41e3e68672a3bf2ffae02d1e
        name: container-image  
